### ISSUE TITLE
Binary Structured Fields

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-httpapi/idempotency#20]
Consider using a binary value rather than a string.  This might not allow higher entropy density, as binary structured fields limit density, but the difference is tiny.

Note: If you are using UUIDs - as people seem to like to do - binary UUIDs expressed in a binary structured field will be smaller than the usual string representation.

**Comment by darrelmiller** [comment]
As a little bit of commentary on this suggestion, I did some testing in .NET using sf-binary, sf-string, parsing both manually and using the StructuredFieldValues library in .NET.

```
GUID  d2f84612-e6bd-4a80-a173-47e7d8f8827b
sf-binary  :Ekb40r3mgEqhc0fn2PiCew==:
sf-string  "d2f84612-e6bd-4a80-a173-47e7d8f8827b"
```
Benchmarking showed the following results
```
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1265/22H2/2022Update/SunValley2)
11th Gen Intel Core i7-11370H 3.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.201
  [Host]     : .NET 7.0.3 (7.0.323.6910), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.3 (7.0.323.6910), X64 RyuJIT AVX2
```
|                        Method |      Mean |    Error |   StdDev |
|------------------------------ |----------:|---------:|---------:|
| ManuallyParseSimpleStringGuid |  37.41 ns | 0.148 ns | 0.131 ns |
|     ManuallyParseSfBinaryGuid |  53.89 ns | 0.718 ns | 0.672 ns |
|         ManuallyParseSfString |  43.57 ns | 0.184 ns | 0.154 ns |
|             ParseSfBinaryGuid |  91.49 ns | 1.625 ns | 1.520 ns |
|                 ParseSfString | 132.09 ns | 1.103 ns | 0.978 ns |

The benchmarks seem to suggest that manual parsing is more efficient, but in reality, the SF library does a lot of validation that that the manual code did not do.  There is obviously a cost for the increased interoperability that SF will bring.  I guess what I am wondering out loud is whether there is going to be appetite to pay the additional costs for the potential for improved interop.  Or is this case an outlier and most headers will be more efficient to parse as a SF?

**Comment by sdatspun2** [comment]
Hi Darrel,

Thanks for the numbers, they do speak. However, I wonder if gains and
losses here make much difference. Since this header is for those http
methods that are not idempotent and those methods do require a payload (for
idempotency use case), typical cost of parsing the payload may dwarf the
cost of parsing the value in the header field. For me, sf-string wins for
easy to debug reasons. Let me know if I am missing something.

Thanks.

**Comment by darrelmiller** [comment]
@sdatspun2 I agree that perf is not a real concern for the origin.  I suspect any potential perf benefits are more for middleboxes who are observing traffic and are not in the business of parsing content.

I'm not 100% sure the debug reasons hold in this case.  Developers don't really care about the value of the uuid, they care that the value in the header is unchanged between requests.  If a developer is looking at raw logs with header values, then comparing the base64 encoded header value is just as easy as comparing the string uuid value.

I don't think it makes a huge difference between sf-binary and sf-string.  I think what is more important is the precedent that it sets for future specifications.  If UUIDs can be represented more compactly as base64 strings and there is no need to worry about folks comparing strings with and without quotes, or comparing strings that differ in case of letters, then I think it is worth considering sf-binary.

**Comment by ekinnear** [comment]
This seems very similar to the discussions that we had around Date -- do we really need the display format to match the serialization format? Given that we're not reading truly "raw" values very much anymore (header compression?), can't we serialize into the most efficient format on the wire and then display in whatever format looks "right" to the user of the tools that are displaying these values?

**Comment by sdatspun2** [comment]
I am closing the issue based on discussion in IETF 116. Syntax 2.1 already indicates sf-string. Will fix some formatting issues of the new draft.

On Apr 14, 2023, at 11:28 AM, Salz, Rich wrote:﻿

There were no disagreements. Authors, please make the change and submit a new draft.  We will then begin a two week working group last call, do the shepherd writeup and ask the IESG for publication. 
 
From: "Salz, Rich" Date: Wednesday, April 5, 2023 at 3:44 PM
To: "[httpapi@ietf.org](mailto:httpapi@ietf.org)"
Subject: [httpapi] UUID as a string in Idempotency-key document

At our meeting last week, we had strong consensus to use sf-string for the UUID field in the idempotency-key draft. If you disagree, please post to the list within a week.
