### ISSUE TITLE
Reuse of idempotency key

### ISSUE THREAD

**Issue by hartmark** [ietf-wg-httpapi/idempotency#22]
```
   If there is an attempt to reuse an idempotency key with a different
   request payload, the resource server SHOULD reply with a HTTP "422"
   status code with body containing a link pointing to relevant
   documentation.  The status code "422" is defined in Section 11.2 of
   [RFC4918].
```

There's no mention if "request payload" includes the URI of the request.

For example having a rest-API where the client sends a JSON-payload like { "user" : "hartmark" } it would be undesirable if it wouldn't respond 422 if that JSON-payload is used at another URI.

**Comment by sdatspun2** [comment]
@hartmark Sorry I don't understand. Can you elaborate with 2 requests here? Thanks.

**Comment by hartmark** [comment]
I don't even myself understand what I posted 😀

I'll close this and reply if I remember what I was thinking
