### ISSUE TITLE
Behaviour when sending Idempotency-Key on other methods than POST or PATCH

### ISSUE THREAD

**Issue by hartmark** [ietf-wg-httpapi/idempotency#23]
`HTTP methods OPTIONS, HEAD, GET, PUT and DELETE are idempotent while methods POST and PATCH are not.`

What is the expected behaviour if the server receives a Idempotency-Key on for example a GET? Is it just ignored?

**Comment by sdatspun2** [comment]
Yes since this header is only applicable for the methods listed it is applicable for.

**Comment by hartmark** [comment]
Okay, thanks for clarifying
