### ISSUE TITLE
Unnecessary and potentially confusing SHOULD

### ISSUE THREAD

**Issue by darrelmiller** [ietf-wg-httpapi/idempotency#26]
> Idempotence is the property of certain operations in mathematics and computer science whereby they can be applied multiple times without changing the result beyond the initial application. It does not matter if the operation is called only once, or 10s of times over. The result SHOULD be the same.

The introduction paragraph ends with the statement "The result SHOULD be the same".  This statement is not needed considering the previous sentence.  Using normative language to refer to the "result" which is not precisely defined, is likely to cause confusion.

**Comment by sdatspun2** [comment]
Will remove, next commit
