### ISSUE TITLE
add appendix about relationship with conditional requests

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/idempotency#4]
some of the design goals of the `Idempotency-Key` header field can also be achieved by using conditional requests as described in RFC 7232. https://blog.container-solutions.com/why-i-stopped-using-post is one example of how to turn create operations into an idempotent interaction without requiring a new header field. it could be useful to point out that alternative design option, and to also point out cases where this alternative design option cannot be used.

**Comment by jayadeba** [comment]
@dret Should this be in scope of this draft at all? This proposal is about how to implement an idempotent POST operation. It is not about describing other implementation alternatives to idempotent POST resource creation operations. What do you think?

**Comment by dret** [comment]
On 2021-07-27 05:27, jayadeba wrote:
> @dret <https://github.com/dret> Should this be in scope of this draft at 
> all? This proposal is about how to implement an idempotent POST 
> operation. It is not about describing other implementation alternatives 
> to idempotent POST resource creation operations. What do you think?

it would be informational, but could be useful info for people looking 
for when to use which pattern. it definitely doesn't have to be part of 
the spec, but personally, i always appreciate when specs provide a bit 
of context for what they do, and how it compares to achieving similar 
goals in other standardized ways.

**Comment by sdatspun2** [comment]
Discussed in 110. @dret where (which section) would you suggest we could include something like this. Should we refer https://datatracker.ietf.org/doc/html/draft-nottingham-http-poe-00 as well?

**Comment by dret** [comment]
On 2021-07-28 00:42, Sanjay Dalal wrote:
> Discussed in 110. @dret <https://github.com/dret> where (which section) 
> would you suggest we could include something like this. Should we refer 
> https://datatracker.ietf.org/doc/html/draft-nottingham-http-poe-00 
> <https://datatracker.ietf.org/doc/html/draft-nottingham-http-poe-00> as 
> well?

all of this probably should go to appendices. @mnot's draft may be less 
important because it never went anywhere. but conditional requests are 
in current RFCs and discussing the relationship there could be helpful 
for readers of the idempotency-key spec.

**Comment by asbjornu** [comment]
I'd just like to give my +1 to the spec explaining its relationship with conditional requests more clearly. Especially for the example mentioned in https://github.com/ietf-wg-httpapi/idempotency/issues/2#issuecomment-877018110 I would expect the server to require an `If-Match` header and respond with `428 Precondition Required` instead of just seemingly allowing lost updates. While I agree that in lieu of a precondition requirement the given example may be correct, I hope to never encounter a server that behaves like that in real life. 😅

**Comment by jayadeba** [comment]
@dret I read the article above- it works when the client provides the resource id for the resource it is trying to create but if client can't provide the resource id the URI semantics `PUT /persons` doesn't sound great. Do we still need to include this in the appendix of the draft. Pls let me know, else we'll close this issue.

**Comment by darrelmiller** [comment]
@dret Do you have an opinion here?

**Comment by dret** [comment]
On 2022-11-06 14:38, Darrel wrote:
> @dret <https://github.com/dret> Do you have an opinion here?

by now i am mostly leaning in the direction of not describing 
alternative approaches. it would be an interesting thing to do, but 
maybe the spec itself is not the best place to do it.

**Comment by sdatspun2** [comment]
thanks. should we close the issue then? we are ready to publish a new draft.

**Comment by sdatspun2** [comment]
Closing for now.
