### ISSUE TITLE
Use Structured Fields

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/idempotency#6]
While not a mandatory requirement for new fields, using SF has a number of benefits:

- Well-defined parsing and serialisation algorithms
- Corresponding reduction of interop and security issues
- Existing implementation support
- Possibility of more efficient serialisation support (i.e., binary HTTP headers)

https://httpwg.org/specs/rfc8941.html

**Comment by sdatspun2** [comment]
Closing this, PR is merged after @mnot comment is addressed.
